### ISSUE TITLE
Make a redirect to the new URL

### ISSUE THREAD

**Issue by ImeevOchir** [tarantool/tarantool-internals#15]
- [ ] https://docs.tarantool.dev/en/latest/ → https://www.tarantool.io/en/dev/core
- [ ] https://docs.tarantool.dev/en/latest/index.html → https://www.tarantool.io/en/dev/core
- [ ] https://docs.tarantool.dev/en/latest/fiber.html → https://www.tarantool.io/en/dev/core/fiber

**Comment by artembo** [comment]
As soon as I assigned to this issue, can I have some details about the task?

**Comment by ImeevOchir** [comment]
The task is to make redirects from outdated site https://docs.tarantool.dev/ to new https://www.tarantool.io/en/dev/core

**Comment by ImeevOchir** [comment]
It was resolved in https://github.com/tarantool/tarantool.io/pull/1235 and external redirects
